#!/usr/bin/env node
/**
 * validate-export [--template <id>|--all] [--keep]
 *
 * Writes a real exported bundle to a temporary directory and checks it two
 * ways, then says which one actually ran.
 *
 *   1. The REFERENCE VALIDATOR. `skills-ref validate <dir>` from the Agent
 *      Skills project (github.com/agentskills/agentskills, MIT, on npm as
 *      `skills-ref`). This is the authority: it parses the frontmatter with a
 *      strict YAML reader and applies the specification's own rules. It needs
 *      the network the first time npx fetches the package.
 *   2. The IN-PROCESS CHECK. `validateBundle` from lib/export.mjs, which
 *      implements the same stated constraints and runs offline. This is what
 *      `npm test` gates on, so `npm test` stays offline.
 *
 * If the reference validator cannot be reached, this tool says so out loud and
 * reports the in-process result instead, rather than printing a pass that came
 * from somewhere weaker than it appears to.
 *
 * It also unzips the bundle with the platform's own extractor, because a zip
 * that only this repo's reader can open is not a zip a visitor can use.
 *
 * Never deploys, never writes inside the repo, and uses `process.exitCode`
 * rather than `process.exit` so nothing is cut off mid-write.
 */

import { mkdtempSync, mkdirSync, writeFileSync, rmSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';
import { pathToFileURL } from 'node:url';
import { TEMPLATES, template, templateSkills } from '../lib/library.mjs';
import { bundleFromTemplate, validateBundle, bundleZip } from '../lib/export.mjs';

/**
 * Running npx on Windows needs a shell.
 *
 * Since Node 18.20/20.12 (the fix for CVE-2024-27980) spawning a `.cmd` file
 * without `shell: true` throws EINVAL, so the reference validator simply never
 * ran and this tool reported "unavailable" for a package that is installed and
 * working. With a shell, Node joins the arguments with spaces and does NOT
 * quote them, so the one argument that can contain a space, the directory, is
 * quoted here. Every value on this command line is generated by `mkdtempSync`
 * or is a literal, so nothing from outside the process reaches it.
 */
const WINDOWS = process.platform === 'win32';
const NPX = WINDOWS ? 'npx.cmd' : 'npx';
const quoteArg = (value) => (WINDOWS ? `"${value}"` : value);

function writeBundle(root, files) {
  for (const file of files) {
    const target = join(root, file.path);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, file.text, 'utf8');
  }
}

/** Run the reference validator over one skill directory. */
function referenceValidate(dir) {
  // On Windows the whole thing is ONE command string rather than an argv array
  // with `shell: true`: Node deprecated that combination (DEP0190) precisely
  // because it concatenates without escaping, and passing the string makes the
  // quoting visible here instead of implied.
  const run = WINDOWS
    ? spawnSync(`${NPX} --yes skills-ref@0.1.5 validate ${quoteArg(dir)}`, { encoding: 'utf8', timeout: 180_000, shell: true })
    : spawnSync(NPX, ['--yes', 'skills-ref@0.1.5', 'validate', dir], { encoding: 'utf8', timeout: 180_000 });
  if (run.error) return { available: false, detail: String(run.error.message) };
  const output = `${run.stdout ?? ''}${run.stderr ?? ''}`.trim();
  // npx prints an install failure to stderr and exits non-zero without ever
  // running the tool. Telling that apart from a real validation failure is the
  // whole point of this function: reporting a fetch problem as a broken bundle
  // would send somebody hunting a defect that is not there.
  if (run.status !== 0 && /(npm error|ENOTFOUND|EAI_AGAIN|could not determine executable|404 Not Found)/i.test(output)) {
    return { available: false, detail: output.split('\n').slice(0, 3).join(' ') };
  }
  return { available: true, ok: run.status === 0, output };
}

/** Ask the platform's own extractor to open the archive. */
function platformUnzip(zipPath, into) {
  if (process.platform === 'win32') {
    const ps = spawnSync('powershell.exe', [
      '-NoProfile', '-NonInteractive', '-Command',
      'Expand-Archive -LiteralPath $env:POLIS_ZIP -DestinationPath $env:POLIS_OUT -Force',
    ], { encoding: 'utf8', env: { ...process.env, POLIS_ZIP: zipPath, POLIS_OUT: into }, timeout: 60_000 });
    if (ps.error) return { available: false, detail: String(ps.error.message) };
    return { available: true, ok: ps.status === 0, output: `${ps.stdout ?? ''}${ps.stderr ?? ''}`.trim(), tool: 'Expand-Archive' };
  }
  const run = spawnSync('unzip', ['-q', '-o', zipPath, '-d', into], { encoding: 'utf8', timeout: 60_000 });
  if (run.error) return { available: false, detail: String(run.error.message) };
  return { available: true, ok: run.status === 0, output: `${run.stdout ?? ''}${run.stderr ?? ''}`.trim(), tool: 'unzip' };
}

function walk(root, prefix = '') {
  const out = [];
  for (const name of readdirSync(root, { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${name.name}` : name.name;
    if (name.isDirectory()) out.push(...walk(join(root, name.name), rel));
    else out.push(rel);
  }
  return out;
}

async function main() {
  const args = process.argv.slice(2);
  const keep = args.includes('--keep');
  const one = args.indexOf('--template') >= 0 ? args[args.indexOf('--template') + 1] : null;
  const ids = one ? [one] : TEMPLATES.map((t) => t.id);

  const root = mkdtempSync(join(tmpdir(), 'polis-export-'));
  let failures = 0;
  let referenceRan = false;

  for (const id of ids) {
    const t = template(id);
    if (!t) {
      process.stdout.write(`unknown template: ${id}\n`);
      failures += 1;
      continue;
    }
    const dir = join(root, id);
    const bundle = bundleFromTemplate({ ...t, skills: templateSkills(t) });
    writeBundle(dir, bundle.files);

    const local = validateBundle(bundle.files);
    process.stdout.write(`\n${id}\n  files: ${bundle.files.length}, warnings: ${bundle.warnings.length}\n`);
    process.stdout.write(`  in-process check: ${local.ok ? 'pass' : 'FAIL'}\n`);
    for (const e of local.errors) process.stdout.write(`    ${e}\n`);
    if (!local.ok) failures += 1;
    for (const w of bundle.warnings) process.stdout.write(`    warning: ${w}\n`);

    const skillsDir = join(dir, 'skills');
    for (const name of existsSync(skillsDir) ? readdirSync(skillsDir) : []) {
      const verdict = referenceValidate(join(skillsDir, name));
      if (!verdict.available) {
        process.stdout.write(`  skills-ref: UNAVAILABLE (${verdict.detail})\n`);
        break;
      }
      referenceRan = true;
      process.stdout.write(`  skills-ref validate skills/${name}: ${verdict.ok ? 'pass' : 'FAIL'}\n`);
      if (!verdict.ok) {
        failures += 1;
        process.stdout.write(`    ${verdict.output.split('\n').join('\n    ')}\n`);
      }
    }

    // And the archive itself, opened by something that is not this repo.
    const zipPath = join(root, `${id}.zip`);
    const bytes = await bundleZip(bundle.files);
    writeFileSync(zipPath, bytes);
    const into = join(root, `${id}-unzipped`);
    mkdirSync(into, { recursive: true });
    const unzipped = platformUnzip(zipPath, into);
    if (!unzipped.available) {
      process.stdout.write(`  platform unzip: UNAVAILABLE (${unzipped.detail})\n`);
    } else if (!unzipped.ok) {
      failures += 1;
      process.stdout.write(`  ${unzipped.tool}: FAIL ${unzipped.output}\n`);
    } else {
      const got = walk(into).sort();
      const want = bundle.files.map((f) => f.path).sort();
      const same = got.length === want.length && got.every((x, i) => x === want[i]);
      if (!same) failures += 1;
      process.stdout.write(`  ${unzipped.tool}: ${same ? 'pass' : 'FAIL'} (${got.length} files, ${bytes.length} bytes)\n`);
      if (!same) process.stdout.write(`    got  ${got.join(', ')}\n    want ${want.join(', ')}\n`);
    }
  }

  process.stdout.write('\n');
  process.stdout.write(
    referenceRan
      ? 'Verification method: the Agent Skills reference validator (skills-ref) ran against the written bundles.\n'
      : 'Verification method: the reference validator could NOT be reached; only the in-process check against the specification constraints ran.\n',
  );
  process.stdout.write(keep ? `bundles kept at ${root}\n` : '');
  if (!keep) rmSync(root, { recursive: true, force: true });
  process.stdout.write(failures ? `${failures} failure(s)\n` : 'all checks passed\n');
  process.exitCode = failures ? 1 : 0;
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
